# Generated by Django 5.1.3 on 2024-11-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=50, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Фото')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.typeproduct')),
            ],
        ),
    ]
